import path from "node:path";
import { fileURLToPath } from "node:url";

import { matchComponents } from "@coderadar/core";
import { describe, expect, it } from "vitest";

import { resolveHookEdges, scanReact } from "./scan.js";

const fixture = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../../../eval/fixtures/d5-generated-code/app",
);

const graph = resolveHookEdges(scanReact({ root: fixture }));

const component = (name: string) =>
  graph.nodes.find((n) => n.kind === "component" && n.name === name);

describe("generated-code classification (6.5, D5)", () => {
  it("flags components generated by directory shape (__generated__/)", () => {
    expect(component("GlyphCatalog")?.flags).toContain("generated");
  });

  it("flags components generated by banner + filename infix (.generated.)", () => {
    expect(component("SchemaViewer")?.flags).toContain("generated");
  });

  it("leaves hand-authored components unflagged", () => {
    expect(component("RevenuePanel")?.flags ?? []).not.toContain("generated");
  });

  it("retains generated data sources in the graph (API metadata)", () => {
    const endpoints = graph.nodes.flatMap((n) =>
      n.kind === "data-source" ? [n.endpoint] : [],
    );
    expect(endpoints).toContain("/api/icons");
    expect(endpoints).toContain("/api/schema");
    expect(endpoints).toContain("/api/revenue");
  });

  it("excludes generated components from match candidates", () => {
    const glyph = matchComponents(graph, { terms: ["Autogenerated glyph catalog"] });
    expect(glyph.status).toBe("declined");
    const schema = matchComponents(graph, { terms: ["Generated schema viewer"] });
    expect(schema.status).toBe("declined");
  });

  it("still resolves hand-authored components", () => {
    const result = matchComponents(graph, { terms: ["Quarterly revenue breakdown"] });
    expect(result.status).toBe("ok");
    expect(result.candidates[0]?.value.component.name).toBe("RevenuePanel");
  });
});
